language: cpp

jobs:
  include:
    - os: linux
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=ON
      compiler: gcc
    - os: linux
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=ON
      compiler: clang
    - os: osx
      osx_image: xcode12.2
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=ON CHECK_STYLE=ON
      compiler: clang
    - os: osx
      osx_image: xcode11.6
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=ON CHECK_STYLE=OFF
      compiler: clang
    - os: osx
      osx_image: xcode10.3
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=OFF CHECK_STYLE=OFF
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=OFF CHECK_STYLE=OFF
      compiler: clang

addons:
  apt:
    packages:
      - libdb++-dev
      - libhwloc-dev
      - libjpeg-dev
      - libopenjp2-7-dev
      - libpng-dev
      - libsqlite3-dev
      - libssl-dev
      - libtiff-dev
      - zlib1g-dev
  homebrew:
    packages:
      - clang-format
      - berkeley-db
      - hwloc
      - jpeg-turbo
      - libpng
      - libtiff
      - openjpeg
      - openssl
      - sqlite
      - zlib

before_install:
    - |
      if [ "${CHECK_STYLE}" == "ON" ] ; then
          echo "Checking coding style with clang-format..."
          clang-format $(find NFIQ2 \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \) -a \! -path '*wsq*' -a \! -name 'RandomForestTrainedParams.h') > clang-format.out
          if [ $(cat clang-format.out | wc -l | tr -d -C '[:digit:]') -ne 0 ]; then
              cat clang-format.out
              git --no-pager diff
              echo "Please run the above files through clang-format using the .clang-format configuration and push your changes to the same branch."
              exit 1
          else
              echo "clang-format finished with no changes"
          fi
      fi

before_script:
    - mkdir build
    - cd build
    - cmake -D32BITS=$BITS_32 -D64BITS=$BITS_64 -DCMAKE_BUILD_TYPE="$CONFIGURATION_TYPE" -DBUILD_NFIQ2_CLI=$BUILD_NFIQ2_CLI ..

script:
    - cmake --build .
