version: 1.0.{build}
branches:
  only:
  - iso_wg3
image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
platform:
  - x64
  - Win32

configuration: Release

cache: c:\tools\vcpkg\installed\

install:
- cmd: git submodule update --init

- cmd: cd C:\Tools\vcpkg
- cmd: git pull
- cmd: .\bootstrap-vcpkg.bat
- cmd: cd %APPVEYOR_BUILD_FOLDER%

- cmd: vcpkg install berkeleydb:x64-windows-static
- cmd: vcpkg install berkeleydb:x86-windows-static

- cmd: vcpkg install getopt:x64-windows
- cmd: vcpkg install getopt:x86-windows

- cmd: vcpkg install hwloc:x64-windows-static
- cmd: vcpkg install hwloc:x86-windows-static

- cmd: vcpkg install libjpeg-turbo:x64-windows-static
- cmd: vcpkg install libjpeg-turbo:x86-windows-static

- cmd: vcpkg install liblzma:x64-windows-static
- cmd: vcpkg install liblzma:x86-windows-static

- cmd: vcpkg install libpng:x64-windows-static
- cmd: vcpkg install libpng:x86-windows-static

- cmd: vcpkg install openjpeg:x64-windows-static
- cmd: vcpkg install openjpeg:x86-windows-static

- cmd: vcpkg install openssl:x64-windows-static
- cmd: vcpkg install openssl:x86-windows-static

- cmd: vcpkg install sqlite3:x64-windows-static
- cmd: vcpkg install sqlite3:x86-windows-static

- cmd: vcpkg install tiff:x64-windows-static
- cmd: vcpkg install tiff:x86-windows-static

- cmd: vcpkg install zlib:x64-windows-static
- cmd: vcpkg install zlib:x86-windows-static

before_build:
- cmd: >-
    md C:\projects\nfiq2\install

    cd C:\projects\nfiq2

    md build\Windows

    cd build\Windows

    cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A %PLATFORM% -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=C:\projects\nfiq2\install -DOPENCV_VERSION="4.4.0" C:\projects\nfiq2

build:
  project: C:\projects\nfiq2\build\Windows\NFIQ2_SUPERBUILD.sln
  verbosity: normal
  parallel: true
